FROM golang:alpine AS builder
RUN apk update && apk add --no-cache git
RUN apk add --no-cache curl
ENV GOPATH /go/
WORKDIR /go/src/github.com/drshrey/darkkitchen/backend/
COPY . .
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
RUN dep ensure
ENV CGO_ENABLED 0
ENV GOCACHE off
CMD ["go", "test", "-v", "./..."]